repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: [--fix]
  - repo: local
    hooks:
      - id: markdown-link-check
        name: markdown-link-check
        entry: python3 scripts/check_markdown_links.py
        language: system
        types: [markdown]
      - id: validate-iso-timestamps
        name: validate-iso-timestamps
        entry: python3 scripts/validate_iso_timestamps.py docs
        language: system
        types: [markdown]
      - id: sync-agents-rules
        name: sync-agents-rules
        entry: python3 scripts/sync_agents_rules.py --check
        language: system
        pass_filenames: false
