name: Docs QA

on:
  pull_request:
    paths:
      - "**/*.md"
      - ".github/workflows/docs-qa.yml"
      - "scripts/**"
  workflow_dispatch:

jobs:
  docs-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint . --config .markdownlint.json

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Validate ISO timestamps
        run: python3 scripts/validate_iso_timestamps.py docs

      - name: Check markdown links
        run: python3 scripts/check_markdown_links.py

      - name: Check TODO CodeLens sidecars
        run: python3 scripts/todos/sync_codelens.py --check
