name: Markdown Linting

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install markdownlint-cli
      run: npm install -g markdownlint-cli
      
    - name: Run markdownlint
      run: markdownlint .
      
    - name: Run markdownlint with auto-fix (check mode)
      run: |
        # Create a temporary directory to test auto-fix
        mkdir -p /tmp/markdownlint-test
        cp -r . /tmp/markdownlint-test/
        cd /tmp/markdownlint-test
        
        # Run auto-fix
        markdownlint --fix . || true
        
        # Check if any files were changed
        if ! git diff --quiet; then
          echo "::warning::Some markdown files can be auto-fixed. Run 'markdownlint --fix .' locally."
          git diff --name-only
        fi
        
    - name: Run custom validations
      run: |
        python3 scripts/check_markdown_links.py
        python3 scripts/validate_iso_timestamps.py docs
        
    - name: Comment on PR with linting results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const { execSync } = require('child_process');
          
          try {
            // Run markdownlint and capture output
            const output = execSync('markdownlint .', { encoding: 'utf8' });
            console.log('No markdownlint issues found');
          } catch (error) {
            const output = error.stdout || error.stderr || '';
            const issueCount = (output.match(/MD\d+/g) || []).length;
            
            const comment = `## 📝 Markdown Linting Results
            
            Found **${issueCount}** markdown linting issues:
            
            \`\`\`
            ${output.substring(0, 4000)}
            \`\`\`
            
            ### How to fix:
            1. Run \`markdownlint --fix .\` to auto-fix most issues
            2. Use \`./scripts/fix-markdown-staged.sh --all\` for staged fixing
            3. Install VS Code markdownlint extension for real-time feedback
            
            ### Configuration:
            - Line length limit: 120 characters
            - Headers: ATX style (# ## ###)
            - Lists: Consistent indentation (2 spaces)
            - Links: Descriptive link text
            - Code: Proper language tags for syntax highlighting`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          }